---

- name: Install nginx
  when: ansible_distribution == "CentOS"
  yum:
    name=nginx
    state=present

- name: Setup Nginx conf
  template:
    src="{{ nginx_conf }}.tpl"
    dest="{{ nginx_path }}/nginx.conf"
#  notify: restart nginx

- name: Ensure engine conf exists
  template:
    src="{{ site_conf }}.tpl"
    dest="{{ nginx_path }}/conf.d/{{ site_conf }}"
