---

- hosts: all
  user: jenkins
  become: true
  gather_facts: False
  vars:
    src_folder: {{ src_folder }}
    working_folder: {{ working_folder }}
    nginx_path: {{ nginx_path }}
  tasks:
     - debug: msg="reading from {{ env_name }}"

- import_playbook: server_conf.yml
